// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXsnYgXKWKBSXidj7z4okQAw60geSyhFI',
    appId: '1:880846666419:web:0b59343ce320fa7d6e0ec6',
    messagingSenderId: '880846666419',
    projectId: 'invoicehub-e4bc2',
    authDomain: 'invoicehub-e4bc2.firebaseapp.com',
    storageBucket: 'invoicehub-e4bc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk63XIPP4tQEJRvqnUNL7QV7ATNM-nd6M',
    appId: '1:880846666419:android:5b09cb6652dd1ed26e0ec6',
    messagingSenderId: '880846666419',
    projectId: 'invoicehub-e4bc2',
    storageBucket: 'invoicehub-e4bc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrDHBQeQUwHtKaqSnbIZ0BmmugS3j6LKk',
    appId: '1:880846666419:ios:45c56fe8404882596e0ec6',
    messagingSenderId: '880846666419',
    projectId: 'invoicehub-e4bc2',
    storageBucket: 'invoicehub-e4bc2.appspot.com',
    androidClientId: '880846666419-697otd41k8gmidnp2ot69b3qgs0uv2im.apps.googleusercontent.com',
    iosClientId: '880846666419-lglkod21a41m3f6tqphrbr8d1a38ft6h.apps.googleusercontent.com',
    iosBundleId: 'com.mumazzad.invoiceProducer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrDHBQeQUwHtKaqSnbIZ0BmmugS3j6LKk',
    appId: '1:880846666419:ios:45c56fe8404882596e0ec6',
    messagingSenderId: '880846666419',
    projectId: 'invoicehub-e4bc2',
    storageBucket: 'invoicehub-e4bc2.appspot.com',
    androidClientId: '880846666419-697otd41k8gmidnp2ot69b3qgs0uv2im.apps.googleusercontent.com',
    iosClientId: '880846666419-lglkod21a41m3f6tqphrbr8d1a38ft6h.apps.googleusercontent.com',
    iosBundleId: 'com.mumazzad.invoiceProducer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Rd5T2NRHiSOK1re2rqVKvUj-2UwoynE',
    appId: '1:880846666419:web:9c01dbabb3fe21ca6e0ec6',
    messagingSenderId: '880846666419',
    projectId: 'invoicehub-e4bc2',
    authDomain: 'invoicehub-e4bc2.firebaseapp.com',
    storageBucket: 'invoicehub-e4bc2.appspot.com',
  );

}